version: '3.8'
services:
  database:
    image: postgres:latest
    container_name: database_Db
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ProductShop
    restart: always
    networks:
      - app-network

volumes:
  db:

networks:
  app-network:
    driver: bridge
