"""empty message

Revision ID: 199559e33744
Revises: 15d2996256c0
Create Date: 2024-12-12 23:26:05.295670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '199559e33744'
down_revision: Union[str, None] = '15d2996256c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Products', sa.Column('count', sa.Integer(), nullable=True))
    op.alter_column('Purchase', 'buyer_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('Purchase_buyer_number_key', 'Purchase', type_='unique')
    op.create_foreign_key(None, 'Purchase', 'Buyers', ['buyer_number'], ['telephone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Purchase', type_='foreignkey')
    op.create_unique_constraint('Purchase_buyer_number_key', 'Purchase', ['buyer_number'])
    op.alter_column('Purchase', 'buyer_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('Products', 'count')
    # ### end Alembic commands ###
