"""empty message

Revision ID: 37967e6e138f
Revises: fec5c927069f
Create Date: 2024-12-10 20:02:41.351125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37967e6e138f'
down_revision: Union[str, None] = 'fec5c927069f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Products', 'descriptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Products', sa.Column('descriptions', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
