"""empty message

Revision ID: ab500d81caf5
Revises: 37967e6e138f
Create Date: 2024-12-10 20:18:19.242349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab500d81caf5'
down_revision: Union[str, None] = '37967e6e138f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PurchasedProducts', sa.Column('count', sa.Integer(), nullable=True))
    op.drop_index('ix_PurchasedProducts_id_product', table_name='PurchasedProducts')
    op.drop_index('ix_PurchasedProducts_id_purchase', table_name='PurchasedProducts')
    op.create_foreign_key(None, 'PurchasedProducts', 'Products', ['id_product'], ['id'])
    op.create_foreign_key(None, 'PurchasedProducts', 'Purchase', ['id_purchase'], ['id_purchase'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'PurchasedProducts', type_='foreignkey')
    op.drop_constraint(None, 'PurchasedProducts', type_='foreignkey')
    op.create_index('ix_PurchasedProducts_id_purchase', 'PurchasedProducts', ['id_purchase'], unique=False)
    op.create_index('ix_PurchasedProducts_id_product', 'PurchasedProducts', ['id_product'], unique=False)
    op.drop_column('PurchasedProducts', 'count')
    # ### end Alembic commands ###
